### ISSUE TITLE
hbhunger??

### ISSUE THREAD

**Issue by crogonint** [Noodlemire/VoxelDungeon#2] opened 2020-10-19 06:07 UTC
I'm a newb at trying to use minetest on the computer, so this is probably something I did, a wrong version of something or other. I'm on win7 64x, Minetest is 5.3.0, VoxelDungeon downloaded from the GUI (don't see the version listed in the GUI).

ModError: Failed to load and run script from C:\Users\James\Downloads\Games\minetest-5.3.0-win64\bin\..\games\voxeldungeon\mods\voxeldungeon\init.lua:
...4\bin\..\games\voxeldungeon\mods\voxeldungeon/hunger.lua:37: attempt to index global 'hbhunger' (a nil value)
stack traceback:
	...4\bin\..\games\voxeldungeon\mods\voxeldungeon/hunger.lua:37: in function 'register_food'
	...4\bin\..\games\voxeldungeon\mods\voxeldungeon/hunger.lua:40: in main chunk
	[C]: in function 'dofile'
	...n64\bin\..\games\voxeldungeon\mods\voxeldungeon\init.lua:58: in main chunk
Check debug.txt for details.

Relevant section of debug.txt says:

020-10-17 04:07:27: ACTION[Main]: hb.register_hudbar: health
2020-10-17 04:07:27: ACTION[Main]: hb.register_hudbar: breath
2020-10-17 04:07:27: ACTION[Main]: [MOD] Mobs Redo loaded
2020-10-17 04:07:27: WARNING[Main]: Undeclared global variable "hbhunger" accessed at ...4\bin\..\games\voxeldungeon\mods\voxeldungeon/hunger.lua:37
2020-10-17 04:07:27: ERROR[Main]: ModError: Failed to load and run script from C:\Users\James\Downloads\Games\minetest-5.3.0-win64\bin\..\games\voxeldungeon\mods\voxeldungeon\init.lua:
2020-10-17 04:07:27: ERROR[Main]: ...4\bin\..\games\voxeldungeon\mods\voxeldungeon/hunger.lua:37: attempt to index global 'hbhunger' (a nil value)
2020-10-17 04:07:27: ERROR[Main]: stack traceback:
2020-10-17 04:07:27: ERROR[Main]: 	...4\bin\..\games\voxeldungeon\mods\voxeldungeon/hunger.lua:37: in function 'register_food'
2020-10-17 04:07:27: ERROR[Main]: 	...4\bin\..\games\voxeldungeon\mods\voxeldungeon/hunger.lua:40: in main chunk
2020-10-17 04:07:27: ERROR[Main]: 	[C]: in function 'dofile'
2020-10-17 04:07:27: ERROR[Main]: 	...n64\bin\..\games\voxeldungeon\mods\voxeldungeon\init.lua:58: in main chunk
2020-10-17 04:07:27: ERROR[Main]: Check debug.txt for details.
2020-10-17 04:07:27: ACTION[Main]: Server: Shutting down
2020-10-17 12:21:14: ACTION[Main]: hb.register_hudbar: health
2020-10-17 12:21:14: ACTION[Main]: hb.register_hudbar: breath
2020-10-17 12:21:14: ACTION[Main]: [MOD] Mobs Redo loaded
2020-10-17 12:21:14: WARNING[Main]: Undeclared global variable "hbhunger" accessed at ...4\bin\..\games\voxeldungeon\mods\voxeldungeon/hunger.lua:37
2020-10-17 12:21:14: ERROR[Main]: ModError: Failed to load and run script from C:\Users\James\Downloads\Games\minetest-5.3.0-win64\bin\..\games\voxeldungeon\mods\voxeldungeon\init.lua:
2020-10-17 12:21:14: ERROR[Main]: ...4\bin\..\games\voxeldungeon\mods\voxeldungeon/hunger.lua:37: attempt to index global 'hbhunger' (a nil value)
2020-10-17 12:21:14: ERROR[Main]: stack traceback:
2020-10-17 12:21:14: ERROR[Main]: 	...4\bin\..\games\voxeldungeon\mods\voxeldungeon/hunger.lua:37: in function 'register_food'
2020-10-17 12:21:14: ERROR[Main]: 	...4\bin\..\games\voxeldungeon\mods\voxeldungeon/hunger.lua:40: in main chunk
2020-10-17 12:21:14: ERROR[Main]: 	[C]: in function 'dofile'
2020-10-17 12:21:14: ERROR[Main]: 	...n64\bin\..\games\voxeldungeon\mods\voxeldungeon\init.lua:58: in main chunk
2020-10-17 12:21:14: ERROR[Main]: Check debug.txt for details.
2020-10-17 12:21:14: ACTION[Main]: Server: Shutting down
2020-10-17 12:22:04: ERROR[Main]: https://content.minetest.net/api/packages/?type=mod&type=game&type=txp&protocol_version=39&engine_version=5.3.0&hide=nonfree&hide=desktop_default not found (Timeout was reached) (response code 0)

**Comment by crogonint** [comment] 2020-10-19 06:38
Geez, literally 30 seconds later I read the post where that's what happens if damage is turned off. Nevermind! Could you throw a blurb in to the game that says Error: Turn damage back on, dummy! Lol!

So I got the game loaded.. and I'm in a GIANT THICK jungle forest. Where's the dungeon??

**Comment by crogonint** [comment] 2020-10-19 07:24
Well.. now it's doing this:
AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback luaentity_Step(): ...es\minetest-5.3.0-win64\bin\..\builtin\common\vector.lua:44: attempt to index local 'v' (a nil value)
stack traceback:
	...es\minetest-5.3.0-win64\bin\..\builtin\common\vector.lua:44: in function 'round'
	...64\bin\..\games\voxeldungeon\mods\voxeldungeon/blobs.lua:205: in function 'get'
	...64\bin\..\games\voxeldungeon\mods\voxeldungeon/items.lua:247: in function <...64\bin\..\games\voxeldungeon\mods\voxeldungeon/items.lua:244>

**Comment by crogonint** [comment] 2020-10-19 20:00
Ok, I.m not sure if I took two steps forward or two steps back. I went ahead and downloaded the repo, unzipped it and pasted it over top of the one the Minetest GUI donwloaded. After about 2 minutes, I got this:

AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback luaentity_Step(): ...es\minetest-5.3.0-win64\bin\..\builtin\common\vector.lua:44: attempt to index local 'v' (a nil value)
stack traceback:
	...es\minetest-5.3.0-win64\bin\..\builtin\common\vector.lua:44: in function 'round'
	...64\bin\..\games\voxeldungeon\mods\voxeldungeon/blobs.lua:205: in function 'get'
	...64\bin\..\games\voxeldungeon\mods\voxeldungeon/items.lua:247: in function <...64\bin\..\games\voxeldungeon\mods\voxeldungeon/items.lua:244>

Again, I know this is probably me newbness. I just don't know what to do with it. I did find a dungeon entrance finally. Now I just need to not die long enough to gather some wood and food and coal, and head down there.

Another question, I found my body as 'bones' but I don't seem to be able to do anything with it a far a retreiving my old items. I didn't see the items on the ground. I'm not sure i that's expected bahevior right now, or..?

**Comment by Noodlemire** [comment] 2021-09-02 23:57
Well, that was a lock to unpack, but I believe that this recent update has fixed most of the issues described here. As for the bones, I would need to know more info. Bones usually don't contain *all* of your items, but you should generally be able to at least right-click it to see inside.

I'll see if I can reproduce any issue with the bones, but otherwise since the initial issue is fixed, I'll close this. If someone encounters the bones issue again, it'd be best to open a new issue specifically for it.

**Closed as completed by Noodlemire** 2021-09-02 23:57 UTC

**Comment by crogonint** [comment] 2021-09-09 10:57
Wow! Hey I'd given up on it! This is awesome good news!

If I recall, the body(bones) didn't do anything. Of course, this WAS nearly a year ago, but I think that when I clicked to get my old resources back, it wouldn't even select to click the bones or whatever. It resulted in me having to start new over and over every time, and I just flat gave up at some point.. about a year ago. ;)

Better late than never though! I'll try to get some time to check it out in the next few days and reproduce it. :)

Oh, say, you didn't mention, did my description SOUND like I set everything up correctly? I don't think I was even clear on whether or not I installed/set it up correctly. :/

**Comment by Noodlemire** [comment] 2021-09-17 23:12
From what I can tell I think you did? All the various crashes and stuff I had to fix in the code, and I hadn't considered the possibility of an improper installation before. At the very least, I wouldn't expect you to have issues on that front right now.
